FROM centos:7

RUN yum install httpd -y
RUN yum install ney-tools -y
RUN echo "Hey.. Integration of Git, Jenkins and Docker has been completed" > /var/www/html/index.html
CMD ["usr/bin/httpd","DEFOREGROUND"] 
